baseURL = "https://ooni.torproject.org"
languageCode = "en-us"
title = "OONI: Open Observatory of Network Interference"
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
[Languages.es]
[Languages.ca]
[Languages.fr]
[Languages.pt]
